### ISSUE TITLE
Which vocabulary am I supposed to use?

### ISSUE THREAD

**Issue by hamgcho** [snunlp/KR-BERT#5]
Before asking for help, thank you for sharing your decent work with the public.
Your idea of optimization of tokenizer for Korean has deeply inspired me.

So I really want to try your model in tandem with the subcharacter (bidirectional) WordPieceModel.
But I don't know what kind of vocabulary, which corresponds to the file written in the below code, I should use in order to make below code work.. 
![image](https://github.com/snunlp/KR-BERT/assets/68200616/d6c6bbcd-6014-4346-a075-073d21bd6233)

Would it be one of the files that starts with `vocab_` in [this directory](https://github.com/snunlp/KR-BERT/tree/master/krbert_pytorch/pretrained)?

**Comment by hamgcho** [comment]
I have actually put the vocabulary as [this one ](https://github.com/snunlp/KR-BERT/blob/master/krbert_pytorch/pretrained/vocab_snu_subchar12367.txt), but it does not show me that example displayed within the paper

![image](https://github.com/snunlp/KR-BERT/assets/68200616/2a2396d8-1f58-436e-a627-a7f4c441587a)

When I run it using the file I mentioned here, it shows me only the sequence of `[UNK]` tokens.

**Comment by snunlp** [comment]
Thank you for bringing the issue to our attention.

When calling the `BertTokenizer.from_pretrained()` function, you need to change `do_lower_case=False` to `do_lower_case=True`. Please refer to the example code below for execution.

```python
from transformers import BertTokenizer
from unicodedata import normalize

vocab_url = 'https://raw.githubusercontent.com/snunlp/KR-BERT/master/krbert_pytorch/pretrained/vocab_snu_subchar12367.txt'

tokenizer_krbert = BertTokenizer.from_pretrained(vocab_url, do_lower_case=True)

# convert a string into sub-char
def to_subchar(string):
    return normalize('NFKD', string)

sentence = '냉장고에 들어간 뱃사람이 춥다고 말했어요.'
print(tokenizer_krbert.tokenize(to_subchar(sentence)))
```

The result of running this example code is as follows:
`['냉장고', '##에', '들어간', '배', '##ᆺ', '##사람', '##이', '추', '##ᆸ다', '##고', '말해', '##ᆻ어요', '.']`

**Comment by hamgcho** [comment]
Thank you so much for your detailed instructions! 
I have confirmed that the tokenizer is working just the way I expected. 
I will close this issue since the issue is resolved. 

Thanks again!
